version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      # Install poetry
      - pip install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies with poetry
      - poetry install --with docs
      # Ensure specific packages are installed
      - pip install sphinx-rtd-theme myst-parser

sphinx:
  configuration: docs/conf.py

# Keep pip requirements in sync
python:
   install:
     - method: pip
       path: .
